const VENDOR = {
  SMOKE_AND_MIRRORS: "SMOKE_AND_MIRRORS",
  SUPER_SPORTS_CARDS: "SUPER_SPORTS_CARDS",
  STAR_CITY_GAMES: "STAR_CITY_GAMES",
  CARD_SHOP_LIVE: "CARD_SHOP_LIVE",
  COLLECTOR_STORE: "COLLECTOR_STORE",
  AMAZON: "AMAZON",
  AMAZON_FREE: "AMAZON_FREE",
  EBAY_PFOOTBALLPETE4DHX: "EBAY_PFOOTBALLPETE4DHX",
  EBAY_THEWASTELANDGAMING: "EBAY_THEWASTELANDGAMING",
  EBAY_CATACLYSMCOLLECTABLES: "EBAY_CATACLYSMCOLLECTABLES",
  EBAY_CACARDSHARK: "EBAY_CACARDSHARK",
  EBAY_CARDRUSHINC: "EBAY_CARDRUSHINC",
  EBAY_FLIPSIDEGAMING: "EBAY_FLIPSIDEGAMING",
  TIME_WARP_COMICS_AND_GAMES: "TIME_WARP_COMICS_AND_GAMES",
  FORTUNA_GAMES: "FORTUNA_GAMES",
  PRIVATE: "PRIVATE",
};

module.exports = VENDOR;
